name: Test
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  test_empack:
    env:
      TARGET_PLATFORM: emscripten-32
      GITHUB_OWNER: 'emscripten-forge'

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        shell: ['bash -l {0}', 'powershell']
        exclude:
         - os: ubuntu-latest
           shell: powershell
         - os: windows-latest
           shell: bash -l {0}

    runs-on: ${{matrix.os}}

    defaults:
      run:
        shell: ${{matrix.shell}}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install mamba and dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci_env.yml
          environment-name: ci-env
          init-shell: >-
              bash
              powershell
          # micromamba-version: '1.4.1'

      - name: Install empack
        run: |
          pip install .

      - name: Install Playwright
        run: |
          playwright install

      - name: Install pyjs-code-runner
        run: |
          python -m pip install git+https://github.com/emscripten-forge/pyjs-code-runner --no-deps --ignore-installed

      - name: Run pytest
        run: |
          pytest -vvv -s tests/
        env:
          EMPACK_DEBUG: "true"

      - name: Run cli from terminal
        run: |
          empack --help
          empack pack --help
